// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Pattern.Repository
{
    using System;
    using System.Collections.Generic;

    public partial class Animal
    {
       public int Id { get; set; }
       public string Name { get; set; }
       public int Legs { get; set; }
       public string Food { get; set; }
       public int FamilyId { get; set; }


        public Family Family { get; set; }

        public Animal()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
