// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Pattern.Repository
{
    using System;
    using System.Collections.Generic;

    public partial class Family
    {
       public int Id { get; set; }
       public string Name { get; set; }

        public ICollection<Animal> Animals { get; set; }

        public Family()
        {
            Animals = new List<Animal>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
