// <auto-generated/>
namespace Pattern.NullObject.Models
{
	public sealed partial class NullHyena : Hyena
	{
		public override bool IsNull => true;

		public override System.String Food => string.Empty;

		public override System.Int32 Legs => default(System.Int32);

		public override System.String Name => string.Empty;
	}
}
